version: "3"
services:
  snitch:
    build: .
    volumes:
      - ./src/:/usr/src/app/src/
      - ./config.json:/usr/src/app/config.json
    restart: always
    networks:
      - dupbit_prime
networks:
  dupbit_prime:
    external: true
